# Generated by Django 3.2.8 on 2021-10-07 04:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='instructor_courses',
            new_name='course_type',
        ),
        migrations.RemoveField(
            model_name='details',
            name='special_courses',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='started_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 4, 36, 41, 275243, tzinfo=utc), verbose_name='started from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='your_choice',
            field=models.BooleanField(default=False),
        ),
    ]
